### ISSUE TITLE
Refactor backend 

### ISSUE THREAD

**Issue by m4xrdk** [amosproj/amos2021ws05-fin-prod-port-quick-check#144]
## User story
1. As a backend developer 
2. I want the backend to be refactored 
3. So that it is easier to work on it afterwards

## Acceptance criteria
* everything which is in the API is fulfilled
* front and backend allignment in advance

## Definition of done
* Approved by product owner
* Tests have been written (e.g. Unit test, integration test etc..)
* Code has been peer reviewed and approved
* No syntax or runtime errors emerged
* Code has to be included in the release candidate

**Comment by InesVogel** [comment]
**TODOs**
- refactor according to Project.yaml Part 1 (import endpoints) 
- [ ] GET, POST /projects
- [ ] GET, PUT /projects/{projectID}
- [ ] GET /productareas

- refactor according to Project.yaml Part 2 (currently not import endpoints) 
- [ ] POST, PUT, DELETE /projects/{projectID}/users

- refactor according to Product.yaml
- [ ] GET, PUT /products/{productID}
- [ ] GET, POST /projects/{projectID}/products

- refactor according to Rating.yaml
- [ ] GET /ratings
- [ ] GET, POST, PUT /projects/{projectID}/ratings
